dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
cache:
  directories:
  - "$HOME/.m2"
before_cache:
  - rm -rf $HOME/.m2/repository/com/autentia/traviscodacy
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE evipdus;'
after_success:
  - ls
  - ls target
  - ls target/jacoco 
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml