DROP DATABASE evipdus;
CREATE DATABASE IF NOT EXISTS evipdus;

ALTER DATABASE evipdus
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE USER 'evipdus'@'%' IDENTIFIED BY 'evipdus';
GRANT ALL PRIVILEGES ON evipdus.* TO 'evipdus'@'%';